import 'package:flutter/material.dart';

List colors = [
  Colors.cyan,
  Colors.cyan[800],
  Colors.cyan[700],
  Colors.cyan[600],
  Colors.cyan[500],
  Colors.cyan[400],
  Colors.cyan[300],
  Colors.lightBlue,
  Colors.lightBlue[900],
  Colors.lightBlue[800],
  Colors.lightBlue[700],
  Colors.lightBlue[600],
  Colors.lightBlue[500],
  Colors.blue,
  Colors.blue[400],
  Colors.blue[500],
  Colors.blue[600],
  Colors.blue[700],
  Colors.blue[800],
  Colors.lightBlueAccent,
  Colors.lightBlueAccent[700],
  Colors.lightBlueAccent[400],
  Colors.lightBlueAccent[100],
];